services:
  cliotedge-backend:
    build:
      context: ./src
    container_name: cliotedge-backend
    ports:
      - "3002:3002"
    env_file:
      - ./src/backend/.env  
    depends_on:
      - cliotedge-postgres
      # - dynamodb-local  
      - mongo
  cliotedge-postgres:
    image: postgres:17
    container_name: cliotedge-postgres
    env_file:
      - ./src/backend/.env  
    ports:
      - "5432:5432"
    volumes:
      - cliotedge-postgres_data:/var/lib/postgresql/data

  # dynamodb-local:
  #   image: amazon/dynamodb-local
  #   container_name: dynamodb-local
  #   ports:
  #     - "8000:8000"
  #   command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
  #   volumes:
  #     - dynamodb_data:/home/dynamodblocal
  #   working_dir: /home/dynamodblocal

  mongo:
    image: mongo:6.0
    ports:
      - "27019:27017"
    env_file:
      - ./src/backend/.env  
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo_data:/data/db

volumes:
  cliotedge-postgres_data:
  # dynamodb_data:
  mongo_data:
