services:
  backend:
    build:
      context: ./src
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./src/backend/.env  
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./src/backend/.env  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

